DROP TABLE IF EXISTS tournament_participation CASCADE;
DROP TABLE IF EXISTS tournaments CASCADE;
DROP TABLE IF EXISTS belt_tests CASCADE;
DROP TABLE IF EXISTS training_participation CASCADE;
DROP TABLE IF EXISTS training_sessions CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS coaches CASCADE;
DROP TABLE IF EXISTS athletes CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Lookup tables
DROP TABLE IF EXISTS tournament_results CASCADE;
DROP TABLE IF EXISTS test_results CASCADE;
DROP TABLE IF EXISTS attendance_status CASCADE;
DROP TABLE IF EXISTS coach_ranks CASCADE;
DROP TABLE IF EXISTS weight_classes CASCADE;
DROP TABLE IF EXISTS belt_ranks CASCADE;
DROP TABLE IF EXISTS genders CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
